name: Run Cypress Tests and Send Email on Failure

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7 AM
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache Cypress
        uses: actions/cache@v3
        id: cypress-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Ensure Cypress Binary
        run: npx cypress install

      - name: Verify Artifact Directories Exist
        run: |
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos
          echo "Artifact directories created"

      - name: Run Cypress Tests
        id: run-cypress
        run: |
          npx cypress run || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
        continue-on-error: true

      - name: Upload Artifacts
        if: failure() && (env.TEST_FAILED == 'true')
        uses: actions/upload-artifact@v4
        with:
          name: cypress-failure-artifacts
          path: |
            cypress/screenshots/**
            cypress/videos/**
          retention-days: 3

      - name: Debug Directory Structure
        if: env.TEST_FAILED == 'true'
        run: |
          echo "Current directory structure:"
          ls -R cypress/screenshots || echo "No screenshots directory"
          ls -R cypress/videos || echo "No videos directory"

      - name: Send Failure Email
        if: env.TEST_FAILED == 'true'
        run: node .github/scripts/send-email.js
        env:
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}